name: Generate Documentation PDF's

on:
  workflow_dispatch:
  push:
    tags:
      - v*

jobs:
  create_PDF:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Publish document
        uses: baileyjm02/markdown-to-pdf@v2
        with:
          input_path: "docs/interface-definitions"
          images_dir: ${{ matrix.directory }}/docs/images
          output_dir: pdfs
          image_import: ../images
          build_html: false
          table_of_contents: true

      - uses: actions/upload-artifact@v4
        with:
          name: interface-definitions
          path: pdfs
